#!/usr/bin/env bash
# another page the redirection must be a “301 Moved Permanently”
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

#sudo sed -i "s/listen 80 defualt_server:/$change/" /etc/nginx/sites-enabled/default
sudo service nginx restart
