#!/usr/bin/env bash
# Script to install and setup nginx

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

change="server_name _;\n\trewrite ^\/redirect_me https:https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$change/" /etc/nginx/site-enabled/default

#creating a 404 error page 

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

stringchange="listen 80 default_server;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$stringchange/" /etc/nginx/site-enabled/default

sudo service nginx restart
