#!/usr/bin/env bash 
#Let’s install the ufw firewall and setup a few rules on web-01
#Configure ufw so that it blocks all incoming traffic,
#except the following TCP ports:
#22 (SSH),443 (HTTPS SSL),80 (HTTP)

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
echo "y" | sudo ufw enable
