#!/usr/bin/env bash
#Nginx is running as the nginx user
pkill -f apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start

